name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcsclite1 libpcsclite-dev

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Typescript
      run: npm install -g typescript

    - name: Install project dependencies
      run: yarn install

    - name: Build
      run: tsc
